server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dnachman/ps-spring-cloudconfig-wa-tolls
          search-paths:
          - 'station*'